### ISSUE TITLE
feature: Support for String ID fields

### ISSUE THREAD

**Issue by shortwavedave** [lrstanley/entrest#76]
### ✨ Describe the feature you'd like

Does entrest support string id fields? e.g.,

```
func (MyModel) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			NotEmpty().
			Unique().
			Immutable().
			Comment("Primary key for MyModel"),
	}
}
```

### 🌧 Is your feature request related to a problem?

I currently get errors like this:

```
internal/database/ent/rest/server.go:614:70: cannot use mymodelID (variable of type int) as string value in argument to mymodel.ID
internal/database/ent/rest/server.go:619:71: cannot use mymodelID (variable of type int) as string value in argument to mymodel.ID
internal/database/ent/rest/server.go:629:56: cannot use mymodelID (variable of type int) as string value in argument to s.db.BlockType.UpdateOneID
internal/database/ent/rest/server.go:634:41: cannot use mymodelID (variable of type int) as string value in argument to s.db.BlockType.DeleteOneID
```

### 🔎 Describe alternatives you've considered

a separate field that is not the primary key

### ⚠ If implemented, do you think this feature will be a breaking change to users?

No

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [ ] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.

**Comment by lrstanley** [comment]
It currently doesn't, but i'd like to add support for it soon, including supporting UUIDs as well (#69).

**Comment by shortwavedave** [comment]
@lrstanley would the PR associated with UUID issue also cover this?

https://github.com/lrstanley/entrest/pull/70

It looks like the template takes in a generic type. Looks like the PR is just waiting for a review, anything I could do to help push along?

**Comment by shortwavedave** [comment]
walking my last comment back - I'm not sure req.tmpl is implemented correctly to support this. Seems like it would try to parse the id as a uuid

**Comment by shortwavedave** [comment]
@lrstanley I started an implementation in the[ referenced branch above](https://github.com/shortwavedave/entrest/commit/4b662293a9606c7a66ed33ce025a0104ba223218), however there are two things we may want to reconcile. 

1. OK to add id to the create params to enable a user to try and set the primary id through the rest interface?
2. the req.tmpl inclusion is clunky, but I'm not sure how best to resolve due to my limited experience with go templating. I created separate functions to handle strings. I think there must be a way to pass in the id type into those helper functions and then deal with them appropriately.

Let me know if you have any thoughts

**Comment by lrstanley** [comment]
@shortwavedave should be resolved as part of https://github.com/lrstanley/entrest/pull/81, once it's merged (will likely do sometime tomorrow if no concerned are raised). Let me know if that doesn't cover the feature set you're looking for. The way I handled the `Req*` related functions isn't great, but as far as I'm aware, ent doesn't expose reusable logic for how it unmarshals. tl;dr: I either have to type cast during runtime, or make the generated code quite a bit longer.

PR includes various other fixes to help make non-integer based IDs more clean, including fixing and improving `AllowClientIDs` (renamed from `AllowClientUUIDs`).
